---
upgrade:
  - |
    Zuul-web now requires access to the Zookeeper keystore.  Ensure that
    the :attr:`keystore.password` option is included in ``zuul.conf``
    on at least the scheduler, executor, and web servers (it may be included
    on all components if desired).
  - |
    Zuul-web requires information for all defined connections.
    Previously, zuul-web may have started without all of the
    connections fully defined in its config file, or with some
    requirements (such as keys used for connecting to remote services)
    present.  They are now required in order for zuul-web to start.
