json_query_change_gate_started: "messages[?contains(@.message, 'Starting gate jobs')]"
json_query_change_gate_ko: "messages[?contains(@.message, 'Patch Set 1: Verified-2')]"
json_query_change_gate_ok: "messages[?contains(@.message, 'Patch Set 1: Verified+2')]"
json_query_change_merged_ok: "messages[?contains(@.message, 'Change has been successfully merged')]"
json_query_change_gate: "{{ json_query_change_gate_ok if pipeline_expected_result == 'ok' else json_query_change_gate_ko }}"
