# Start the quickstart tutorial with `docker-compose -p zuul-tutorial
# up` (as directed in the instructions) in order for the network to
# have the expected name so that it can be shared with keycloak.

# Version 2.1 is required to specify the network name
version: '2.1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=kcadmin
      - KC_HTTP_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - "./keycloak/:/opt/keycloak/data/import/:z"
    command:
      - start-dev
      - --import-realm
    networks:
      - zuul

networks:
  zuul:
    external: true
    name: zuul-tutorial_zuul
