- block:
    - name: Install git-review
      package:
        name:
          - git-review
          - podman-compose
        state: present
      become: true
  when: not local

- name: Setup Tutorial Execution
  include_role:
    name: setup-tutorial

- name: Run quick-start tutorial
  include_tasks: quick-start.yaml

- name: Run admin tutorial
  include_tasks: admin.yaml

- name: Run tracing tutorial
  include_tasks: tracing.yaml
